name: Build & test

on: [push, pull_request]

jobs:
  linux:
    uses: przemek83/common/.github/workflows/build-and-test-cpp.yml@main
    with:
      platform: ubuntu-latest
      dependencies-linux: "libgl1-mesa-dev libxcursor-dev"

  windows:
    uses: przemek83/common/.github/workflows/build-and-test-cpp.yml@main
    with:
      platform: windows-latest